services:
    orangegate.core.date.moment_format_converter:
        class: Symbio\OrangeGate\AdminBundle\Date\MomentFormatConverter

    orangegate.core.form.type.date_picker:
        class: Symbio\OrangeGate\AdminBundle\Form\Type\DatePickerType
        tags:
            - { name: form.type, alias: orangegate_type_date_picker }
        arguments: ['@orangegate.core.date.moment_format_converter']

    orangegate.core.form.type.datetime_picker:
        class: Symbio\OrangeGate\AdminBundle\Form\Type\DateTimePickerType
        tags:
            - { name: form.type, alias: orangegate_type_datetime_picker }
        arguments: ['@orangegate.core.date.moment_format_converter']

    orangegate.admin.form.type.string:
        class: Symbio\OrangeGate\AdminBundle\Form\Type\StringType
        tags:
            - { name: form.type, alias: string }

    orangegate.admin.form.type.autocomplete:
        class: Symbio\OrangeGate\AdminBundle\Form\Type\AutocompleteType
        tags:
            - { name: form.type, alias: orangegate_type_autocomplete }

    orangegate.admin.form.type.sortable_entity:
        class: Symbio\OrangeGate\AdminBundle\Form\Type\SortableEntityType
        tags:
            - { name: form.type, alias: orangegate_type_sortable_entity }
        arguments: [ @doctrine, @property_accessor ]

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    orangegate.admin.block.formatter:
        class: Symbio\OrangeGate\AdminBundle\Block\FormatterBlockService
        tags:
            - { name: sonata.block }
        arguments: [ sonata.block.empty, @templating, @translator ]

    orangegate.twig_extension:
        class: Symbio\OrangeGate\AdminBundle\Twig\OrangeGate4Extension
        public: false
        tags:
            - { name: twig.extension }

    twig.extension.stringloader:
        class: Twig_Extension_StringLoader
        tags:
            - { name: twig.extension }

    orangegate.formatter.form.type.simple:
        class: Symbio\OrangeGate\AdminBundle\Form\Type\SimpleFormatterType
        arguments: [@ivory_ck_editor.config_manager]
        tags:
            - { name: form.type, alias: orangegate_simple_formatter_type }

    sonata.admin.object.manipulator.acl.admin:
        class: Symbio\OrangeGate\AdminBundle\Util\AdminObjectAclManipulator
        arguments: [@form.factory, Sonata\AdminBundle\Security\Acl\Permission\MaskBuilder]
        calls:
            - [ setContainer, [@service_container] ]

    orangegate.admin.form.type.dynamic_choice:
        class: Symbio\OrangeGate\AdminBundle\Form\Type\DynamicChoiceType
        tags:
            - { name: form.type, alias: orangegate_type_dynamic_choice }

    orangegate.core.form.type.filesystem_choice:
        class: Symbio\OrangeGate\AdminBundle\Form\Type\FilesystemChoiceType
        tags:
            - { name: form.type, alias: orangegate_filesystem_choice_type }
        arguments: [ @kernel ]

